"""add sticker_count to users

Revision ID: 03c480f31a4c
Revises: 2558ec1b7eed
Create Date: 2026-04-03 19:41:01.543884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c480f31a4c'
down_revision: Union[str, Sequence[str], None] = '2558ec1b7eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sticker_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sticker_count')
    # ### end Alembic commands ###
