"""enforce media_assets constraints and finalize post_images migration

Revision ID: 2558ec1b7eed
Revises: fb213458d04c
Create Date: 2026-02-24 21:35:31.313066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2558ec1b7eed'
down_revision: Union[str, Sequence[str], None] = 'fb213458d04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_assets', 'uploader_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('media_assets', 'file_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('media_assets', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ATTACHED', name='asset_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::asset_status_enum"))
    op.alter_column('post_images', 'asset_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('post_images', 'filename')
    op.drop_column('post_images', 'upload_time')
    op.drop_column('post_images', 'json_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_images', sa.Column('json_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('post_images', sa.Column('upload_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('post_images', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('post_images', 'asset_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('media_assets', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ATTACHED', name='asset_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::asset_status_enum"))
    op.alter_column('media_assets', 'file_url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('media_assets', 'uploader_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
