"""add media_assets table and prepare post_images for migration

Revision ID: 9a8c9e386289
Revises: bcf7ddb6972c
Create Date: 2026-02-24 21:09:48.552834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a8c9e386289'
down_revision: Union[str, Sequence[str], None] = 'bcf7ddb6972c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uploader_id', sa.BigInteger(), nullable=True),
    sa.Column('file_url', sa.String(length=1024), nullable=True),
    sa.Column('json_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ATTACHED', name='asset_status_enum'), server_default=sa.text("'PENDING'::asset_status_enum"), nullable=True),
    sa.Column('upload_time', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post_images', sa.Column('asset_id', sa.BigInteger(), nullable=True))
    op.alter_column('post_images', 'json_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_foreign_key(None, 'post_images', 'media_assets', ['asset_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_images', type_='foreignkey')
    op.alter_column('post_images', 'json_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('post_images', 'asset_id')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
