-- ============================================================
-- V1__init_schema.sql
-- Initial schema for messaging service
-- Run by Flyway on first startup before JPA validation
-- ============================================================

-- ------------------------------------------------------------
-- CONVERSATIONS
-- last_message_id is intentionally nullable — stays nullable
-- forever. New conversations have no messages yet. The FK to
-- messages is added below as DEFERRABLE INITIALLY DEFERRED to
-- handle the circular dependency within a single transaction.
-- ------------------------------------------------------------
CREATE TABLE conversations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name         VARCHAR(100),
    group_avatar       VARCHAR(255),
    last_message_id    BIGINT,                         -- FK added below (circular dep)
    last_activity_at   TIMESTAMPTZ NOT NULL,
    is_group           BOOLEAN     NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ------------------------------------------------------------
-- MESSAGES
-- message_id is a backend-generated snowflake — NOT an identity
-- column. The application layer sets it before persist.
-- client_message_id + sender is the idempotency key.
-- sender references users in the auth schema (read-only access).
-- ------------------------------------------------------------
CREATE TABLE messages (
    message_id              BIGINT      PRIMARY KEY,   -- snowflake set by app
    client_message_id       UUID        NOT NULL,
    conversation_id         BIGINT      NOT NULL REFERENCES conversations(id),
    sender                  BIGINT      NOT NULL,      -- FK to auth.users (read-only, not enforced here)
    time_sent               TIMESTAMPTZ NOT NULL,
    edited_at               TIMESTAMPTZ,
    reply_to_message_id     BIGINT      REFERENCES messages(message_id),
    content                 TEXT        NOT NULL,
    content_type            VARCHAR(10) NOT NULL
                                CHECK (content_type IN ('text','image','video','audio','file')),
    deleted_at              TIMESTAMPTZ,               -- soft delete, never hard delete
    UNIQUE (client_message_id, sender)                 -- idempotency constraint
);

-- ------------------------------------------------------------
-- CIRCULAR FK — added after both tables exist.
-- DEFERRABLE INITIALLY DEFERRED: Postgres only validates this
-- FK at transaction COMMIT, not mid-transaction. This allows
-- INSERT message + UPDATE conversation.last_message_id in one
-- transaction without ordering constraints.
-- ------------------------------------------------------------
ALTER TABLE conversations
    ADD CONSTRAINT fk_conversations_last_message
    FOREIGN KEY (last_message_id)
    REFERENCES messages(message_id)
    DEFERRABLE INITIALLY DEFERRED;

-- ------------------------------------------------------------
-- CONVERSATION_PARTICIPANTS
-- Composite PK on (conversation_id, user_id).
-- last_read_message_id drives unread counts and reconnect sync.
-- user_id references auth schema users — not a DB-enforced FK.
-- ------------------------------------------------------------
CREATE TABLE conversation_participants (
    conversation_id         BIGINT      NOT NULL REFERENCES conversations(id),
    user_id                 BIGINT      NOT NULL,      -- auth schema, not DB-enforced FK
    joined_at               TIMESTAMPTZ NOT NULL,
    left_at                 TIMESTAMPTZ,
    is_active               BOOLEAN     NOT NULL DEFAULT TRUE,
    last_read_message_id    BIGINT      REFERENCES messages(message_id),
    role                    VARCHAR(10) CHECK (role IN ('member', 'admin')),
    PRIMARY KEY (conversation_id, user_id)
);

-- ------------------------------------------------------------
-- MESSAGE_STATUSES
-- Per-recipient status tracking. Optional for now — schema is
-- laid out for future per-recipient read receipt support,
-- primarily useful for group chats.
-- ------------------------------------------------------------
CREATE TABLE message_statuses (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  BIGINT      NOT NULL REFERENCES messages(message_id),
    user_id     BIGINT      NOT NULL,
    status      VARCHAR(10) NOT NULL CHECK (status IN ('sent','delivered','read'))
);

-- ------------------------------------------------------------
-- MESSAGE_REACTIONS
-- Unique constraint prevents duplicate reactions per user per message.
-- ------------------------------------------------------------
CREATE TABLE message_reactions (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  BIGINT      NOT NULL REFERENCES messages(message_id),
    user_id     BIGINT      NOT NULL,
    reaction    VARCHAR(10) NOT NULL,
    UNIQUE (message_id, user_id, reaction)
);

-- ============================================================
-- INDEXES
-- ============================================================

-- Core index for unread count query and cursor-based pagination.
-- Both queries filter on conversation_id then range-scan on message_id.
CREATE INDEX idx_messages_conversation_message
    ON messages(conversation_id, message_id);

-- Lookup index for idempotency check on incoming messages.
CREATE INDEX idx_messages_client_message_id
    ON messages(client_message_id);

-- Participant lookup — used when iterating online members for delivery
-- and when checking if a user belongs to a conversation.
CREATE INDEX idx_participants_user_id
    ON conversation_participants(user_id);

-- Status lookup per message — used for bulk delivered ack on reconnect.
CREATE INDEX idx_message_statuses_message_id
    ON message_statuses(message_id);

